""" Desempaquetando listas """

NUMEROS = [1, 2, 3]

PRIMERO, SEGUNDO, TERCERO = NUMEROS
print(PRIMERO, SEGUNDO, TERCERO)

PRIMERO, *OTROS = NUMEROS
print(PRIMERO, OTROS)

NUMEROS = list(range(1, 11))
PRIMERO, SEGUNDO, *OTROS = NUMEROS
print(PRIMERO, SEGUNDO, OTROS)

PRIMERO, *OTROS, ULTIMO = NUMEROS
print(PRIMERO, OTROS, ULTIMO)
